config/routes.rb
Rails.application.routes.draw do
  resources :channels do
    resource :channel_user
    resources :messages
  end

  devise_for :users
  root 'channels#index'

  #resources :notifications, only: [:index]
  resources :notifications

  #get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :channel_users, dependent: :destroy
  has_many :users, through: :channel_users

  has_many :messages, dependent: :destroy
  validates :name, presence: true
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :authenticate_user!, exception: [:index]
  before_action :set_channel, only: %i[ show edit update destroy ]

  # GET /channels or /channels.json
  def index
    @channels = Channel.all
  end

  # GET /channels/1 or /channels/1.json
  def show
    puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    puts current_user.username
    puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    @channel_user = current_user.channel_users.find_by(channel: @channel)
    @last_read_at = @channel_user&.last_read_at || @channel.created_at #이게 뭘까
    @channel_user&.touch(:last_read_at) #이게 뭘까
    # message_channel.rb에 touch를 def하긴 하는데 그거 아닐까?
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels or /channels.json
  def create
    puts params
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to channel_url(@channel), notice: "Channel was successfully created." }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1 or /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to channel_url(@channel), notice: "Channel was successfully updated." }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1 or /channels/1.json
  def destroy
    #@channel.destroy!
    @channel.destroy

    respond_to do |format|
      format.html { redirect_to channels_url, notice: "Channel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def channel_params
      params.require(:channel).permit(:name)
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
  def active_channel?(channel)
    channel == @channel
  end
end

app/views/channels/_channel.html.erb
<div id="<%= dom_id channel %>">
  <p>
    <strong>Name:</strong>
    <%= channel.name %>
  </p>

</div>

app/views/channels/_form.html.erb
<%= form_with(model: channel, local: true) do |form| %>
  <% if channel.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
        <% channel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <% if channel.persisted? %>
      <div class="float-right">
        <%= link_to "Destroy", channel, method: :delete, class: "text-danger", data: { confirm: "Are you sure" } %>
      </div>
    <% end %>

    <%= form.submit class: "btn btn-primary" %>

  <% if channel.persisted? %>
    <%= link_to "Cancel", channel, class: "btn btn-link" %>
  <% else %>
    <%= link_to "Cancel", channels_path, class: "btn btn-link" %>
  <% end %>

  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing channel</h1>

<%= render "form", channel: @channel %>

app/views/channels/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="row">
  <div class="col-sm-6">
    <h1>Channels</h1>
  </div>

  <div class="col-sm-6 text-right">
    <%= link_to "Add New channel", new_channel_path, class: "btn btn-primary" %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
      <% @channels.each do |channel| %>
        <%= content_tag :tr, id: dom_id(channel), class: dom_class(channel) do %>
          <td><%= link_to channel.name, channel %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/channels/new.html.erb
<h1>New channel</h1>

<%= render "form", channel: @channel %>

app/views/channels/show.html.erb
<div class="row" data-controller="channel" data-channel-id="<%= @channel.id %>">
  <div class="col-sm-2">
    <%= render "shared/sidebar" %>
  </div>

  <div class="col-sm-10 relative">
    <div class="d-flex justify-content-between sticky-top bg-white border-bottom pt-2">
      <strong>#<%= @channel.name %></strong>

      <div>
        <%= link_to "Leave", channel_channel_user_path(@channel), data: {turbo_method: :delete}, class: "btn btn-link" %>
      </div>
    </div>

    <%#<div data-target="channel.messages">%>
    <div data-channel-target="messages">
      <%= render @channel.messages %>
    </div>

    <div style="height:50px;"></div>

    <div class="fixed-bottom row">
      <div class="col-sm-10 offset-sm-2 p-2 bg-white">
        <% if current_user.channels.include?(@channel) %>
          <%#= form_with model: [@channel, Message.new], data: { action: "ajax:success->channel#clearMessage" } do |form| %>
            <%= form_with model: [@channel, Message.new], data: { action: "turbo:submit-end->channel#clearMessage" } do |form| %>
            <%#= form.text_field :body, placeholder: "Message ##{@channel.name}", class: "form-control", data: { target: "channel.newMessage" } %>
            <%= form.text_field :body, placeholder: "Message ##{@channel.name}", class: "form-control", data: { channel_target: "newMessage" } %>
          <% end %>
        <% else %>
          <%= link_to "Join #{@channel.name}", channel_channel_user_path(@channel), data: {turbo_method: :post} %>
        <% end %>
      </div>
    </div>

  </div>
</div>