config/routes.rb
Rails.application.routes.draw do
  resources :channels do
    resource :channel_user
    resources :messages
  end

  devise_for :users
  root 'channels#index'

  #resources :notifications, only: [:index]
  resources :notifications

  #get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light fixed-top">
  <div class="container mx-auto">
    <%= link_to root_path, class: "navbar-brand" do %>
      GroupChat
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>

      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <%= yield :right_nav %>

          <li class="nav-item">
            <%= link_to notifications_path, class: "nav-link" do %>
              <span><i class="far fa-bell" aria-hidden="true"></i></span>
            <% end %>
          </li>

          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-expanded="false">
              <%= current_user.username %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-success me-2" %></li>
          <li><%= link_to "Login", new_user_session_path, class: "btn btn-outline-secondary" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notices.html.erb
<% flash.each do |msg_type, message| %>
  <div class="alert <%= bootstrap_class_for(msg_type) %> mt-5">
    <div class="container">
      <button class="close" data-dismiss="alert"><span>x</span></btn>
      <%= message %>
    </div>
  </div>
<% end %>

app/views/shared/_sidebar.html.erb
<div class="sticky-top pt-3">
  <div class="d-flex justify-content-between">
    <h6>Channels</h6>
    <%= link_to icon("fas", "plus"), new_channel_path %>
  </div>

  <ul class="list-group">
    <% Channel.all.each do |channel| %>

      <li data-controller="unreads" data-unreads-id=<%= channel.id %> class="list-group-item d-flex justify-content-between align-items-center">
        <%= link_to_if !active_channel?(channel), channel.name, channel %>
        <span data-unreads-target="mentions" class="badge bg-danger rounded-pill fw-bold text-white" hidden>0</span>
        <!-- span을 둘러싸고 있던 if 때문에 target이 적용되지 않은 듯! -->
      </li>
      <%#= tag.li data: { controller: "unreads", unreads_id: channel.id }, class: ["list-group-item d-flex justify-content-between align-items-center", ("active" if active_channel?(channel))] do %>
        <%#= link_to_if !active_channel?(channel), channel.name, channel %>
        <%# if !active_channel?(channel) %>
        <!--<span data-unreads-target="mentions" class="badge badge-primary badge-pill" hidden>0</span>-->
        <%# end %>
    <% end %>
  </ul>

  <hr />

  <div class="d-flex justify-content-between">
    <h6>Users</h6>
  </div>
  <% @channel.users.each do |user| %>
    <div>
      <%= user.username %>
    </div>
  <% end %>
</div>